### PR TITLE
Devenv instructions

### PR DESCRIPTION
**Pull request by karlmdavis**
@sbrockhoff Could you please review this, which is part of http://issues.hhsdevcloud.us/browse/CBBI-33? This should be the full set of instructions that are shared between all of the Java-based Blue Button projects.

Instructions specific to each project will be documented in those projects (and separate pull requests for those are coming).

If you think it looks good, just give it a :+1: ("`:+1:`") or somesuch.

### CODE REVIEW

**Comment by sbrockhoff** [comment]
I attempted to run the python script via cygwin and get the below error. The script calls out "unzip" and "cabextract" as other packages needed to run the script, but the readme only calls out python3. Should these 2 packages also be added to the readme?

```
Install JDK
   - Downloading jdk-8u66-windows-x64.exe... downloaded.
   - Extracting jdk-8u66-windows-x64... Traceback (most recent call last):
  File "./devenv-install.py", line 782, in <module>
    main()
  File "./devenv-install.py", line 56, in main
    jdk_install_path = jdk_install(jdk_archive_path)
  File "./devenv-install.py", line 147, in jdk_install
    jdk_extract_exe(jdk_archive_path, jdk_install_path)
  File "./devenv-install.py", line 181, in jdk_extract_exe
    stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'cabextract'
```

**Comment by karlmdavis** [comment]
Good catch: Will update. If you install those, too, does it work?

**Comment by sbrockhoff** [comment]
Initially I got a permission denied error but after running Cygwin as an administrator I was able to get past the Eclipse install. At this point, i'm getting a permission error attempting to install the Ecilpse Maven Integration plugin. Any suggestions?

```
* Install Eclipse Plugins
   - Installing Maven Integration for Eclipse JDT APT... Traceback (most recent              call last):
  File "./devenv-install.py", line 782, in <module>
    main()
  File "./devenv-install.py", line 63, in main
    eclipse_install_plugins(eclipse_install_path)
  File "./devenv-install.py", line 413, in eclipse_install_plugins
    stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by karlmdavis** [comment]
Hmm... I think I remember you saying that you only had admin access to a specific folder on your drive? If so, that's kind of a weird situation that the script wasn't really designed to support.

On the other hand, it actually _was_ designed to support the complete lack of admin permissions that I have on my CMS laptop. But in order for it to work, you've got to ensure that Cygwin (and everything in it) is installed as a user. After downloading the Cygwin installer, here's the command I used to install Cygwin as a user (adjust the paths to match your user dirs):

```
> setup-x86_64.exe --no-admin --quiet-mode --arch x86_64 --site http://mirror.cs.vt.edu/pub/cygwin/cygwin/ --only-site --root C:\Users\D6LU\apps\cygwin64 --local-package-dir C:\Users\D6LU\apps\cygwin64\packages-local --packages lynx --no-desktop
```

This worked great! Up until I needed git-lfs, which I couldn't manage to install as a user. Since you've got _some_ admin access though (unlike me), you might be able to get past that.

But if not, I'd recommend filing a bug for this and we can write off the script's Windows support for now -- instead just install things manually.

Thoughts?

**Comment by sbrockhoff** [comment]
Yes I do just have install permissions to a specific folder, but typically if any file installations get blocked I will get a security popup listing the file(s) in question. I didn’t get any notifications though so I think that it must be something else.

I think the installation of the JDK/Eclipse/Plugin is straightforward enough we could just have people install it manually though for the Windows side.

**Comment by sbrockhoff** [comment]
Just a couple other comments/questions to close this out:
1. I ran into the toolchains.xml issue again and had to create that, so it may be worthwhile to add in a step to create that file and point it to a jdk8 instance.
2. I was able to get through the GPG setup, and it signs the pom successfully, but fails to deploy the snapshot

`[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy (injected-nexus-deploy) on project bluebutton-parent: Failed to deploy artifacts: Could not transfer artifact gov.hhs.cms.bluebutton:bluebutton-parent:pom.asc:1.1.1-20160614.223219-1 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Access denied to https://oss.sonatype.org/content/repositories/snapshots/gov/hhs/cms/bluebutton/bluebutton-parent/1.1.1-SNAPSHOT/bluebutton-parent-1.1.1-20160614.223219-1.pom.asc. Error code 401, Unauthorized -> [Help 1]`

Not sure if I'm just missing access or a misunderstanding on my part about what all gets deployed to Maven Central. Would all the snapshots/releases going out to Maven Central get built via Jenkins rather than local builds anyways?

**Comment by karlmdavis** [comment]
@sbrockhoff: Could you review my additions from just now?

**Comment by sbrockhoff** [comment]
Even after getting access to deploy, I still receive Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/gov/hhs/cms/bluebutton/bluebutton-parent/1.1.1-SNAPSHOT/bluebutton-parent-1.1.1-20160707.162624-1.pom.asc. Return code is: 401, ReasonPhrase: Unauthorized.

However, I'm still not sure that there is really a need to be able to deploy snapshots from my local environment is there?

**Comment by karlmdavis** [comment]
@sbrockhoff Probably not, but if that's not working, then you likely don't have permissions to deploy releases, either. To avoid [bus factor](https://en.wikipedia.org/wiki/Bus_factor) concerns, I think it's important that my account not be the only one with those permissions.

Can you add the `settings.xml` entry I mentioned in my commit from just a minute ago, and try again?

**Comment by sbrockhoff** [comment]
I still get:
Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy (injected-nexus-deploy) on project bluebutton-parent: Failed to deploy artifacts: Could not transfer artifact gov.hhs.cms.bluebutton:bluebutton-parent:pom.asc:1.1.1-20160711.145436-1 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Access denied to https://oss.sonatype.org/content/repositories/snapshots/gov/hhs/cms/bluebutton/bluebutton-parent/1.1.1-SNAPSHOT/bluebutton-parent-1.1.1-20160711.145436-1.pom.asc. Error code 401, Unauthorized -> [Help 1]

If I just try to go to the repo in the browser, for instance https://oss.sonatype.org/content/repositories/snapshots/gov/hhs/ I do not see a cms folder out there. Have any snapshots been published previously for this project?

**Comment by sbrockhoff** [comment]
Worked after fixing settings.xml file. :+1:

**Pull request merged**
